ERROR REPORT DATETIME 2021-06-29 12:54:57.925413-------------------- ERROR IN FILE 96449_doc20210105094602172380 --------------------
[<FrameSummary file C:/Users/Utente/Documents/Multitraccia/Progetti/Cobat/OCR_development/NEW_OCR/main_OCR.py, line 1243 in <module>>, <FrameSummary file C:/Users/Utente/Documents/Multitraccia/Progetti/Cobat/OCR_development/NEW_OCR/main_OCR.py, line 129 in get_dataframe>]
Exception - tuple index out of range
